# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-14 04:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170914_0341'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
