# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 02:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170123_1158'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-publish', '-timestamp', '-updated']},
        ),
    ]
