# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 09:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_read_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='read_time',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
