# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-14 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20170914_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='loc_type',
            field=models.CharField(blank=True, choices=[('Streetfood', 'Streetfood'), ('Cheap Restaurant', 'Cheap Restaurant'), ('Restaurant', 'Restaurant'), ('Fine Dining', 'Fine Dining'), ('Delivery Only', 'Delivery Only')], max_length=40, null=True),
        ),
    ]
