# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-14 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20170914_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='cuisine',
            field=models.CharField(choices=[('vegetarian', 'vegetarian'), ('thai', 'thai'), ('chinese', 'chinese'), ('korean', 'korean'), ('fusion', 'fusion'), ('indian', 'indian'), ('french', 'french'), ('italian', 'italian'), ('mexican', 'mexican'), ('american', 'american'), ('vietnamese', 'vietnamese'), ('other', 'other')], max_length=40),
        ),
    ]
