# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-17 07:43
from __future__ import unicode_literals

import blog.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20170914_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=blog.models.get_image_filename, verbose_name='Image')),
                ('location', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='blog.Location')),
            ],
        ),
    ]
