# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-17 14:58
from __future__ import unicode_literals

import blog.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=blog.models.upload_location, verbose_name='Image')),
                ('location', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='blog.Location')),
            ],
        ),
        migrations.RemoveField(
            model_name='images',
            name='location',
        ),
        migrations.DeleteModel(
            name='Images',
        ),
    ]
